name: 3.2$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPack: 'Application'
  SolutionName: 'MLH.RestExtensions.sln'
  ApplicationSubPath: 'MLH.RestExtensions'



jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    name: 'Hosted VS2017'
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      SolutionName: $(SolutionName)
      ApplicationSubPath: $(ApplicationSubPath)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Pack_And_Publish_To_NuGet.yaml@ALMStuff
    parameters:
      FolderToPack: $(FolderToPack)
